name: gmsc
channels:
  - conda-forge
dependencies:
  - python=3.11
  - pip
  - numpy
  - pandas
  - scikit-learn
  - xgboost
  - matplotlib
  - seaborn
  - shap
  - jupyterlab
  - ipykernel
  - pyarrow
  - pip:
      - kaggle
